scripts: mount data partition before action

diff --git a/utils/lib/wb-image-update/postinst/20log-factoryreset b/utils/lib/wb-image-update/postinst/20log-factoryreset
--- a/utils/lib/wb-image-update/postinst/20log-factoryreset
+++ b/utils/lib/wb-image-update/postinst/20log-factoryreset
@@ -22,7 +22,15 @@ flag_set() {
 	echo "$FLAGS" | grep -- "--$1" >/dev/null 2>&1
 }
 
-WB_RESTORE_DIR="/mnt/data/.wb-restore/.logs"
+DATA_MOUNT=$(mktemp -d)
+mount /dev/mmcblk0p6 "$DATA_MOUNT" || {
+    echo "Failed to mount /dev/mmcblk0p6 to $DATA_MOUNT"
+    exit 1
+}
+
+trap 'umount $DATA_MOUNT; rmdir $DATA_MOUNT' EXIT
+
+WB_RESTORE_DIR="$DATA_MOUNT/.wb-restore/.logs"
 
 if flag_set "factoryreset" ; then
     echo "Saving information about this factory reset"
diff --git a/utils/lib/wb-image-update/postinst/30save-fit b/utils/lib/wb-image-update/postinst/30save-fit
--- a/utils/lib/wb-image-update/postinst/30save-fit
+++ b/utils/lib/wb-image-update/postinst/30save-fit
@@ -21,13 +21,21 @@ flag_set() {
 	echo "$FLAGS" | grep -- "--$1" >/dev/null 2>&1
 }
 
-WB_RESTORE_DIR="/mnt/data/.wb-restore"
-TARGET_FIT="$WB_RESTORE_DIR/factoryreset.fit"
-
 if ! flag_set "factoryreset" ; then
     echo "Skipping FIT save"
     exit
 fi
+
+DATA_MOUNT=$(mktemp -d)
+mount /dev/mmcblk0p6 "$DATA_MOUNT" || {
+    echo "Failed to mount /dev/mmcblk0p6 to $DATA_MOUNT"
+    exit 1
+}
+
+trap 'umount $DATA_MOUNT; rmdir $DATA_MOUNT' EXIT
+
+WB_RESTORE_DIR="$DATA_MOUNT/.wb-restore"
+TARGET_FIT="$WB_RESTORE_DIR/factoryreset.fit"
 
 if [ -n "$FIT" ]; then
     echo "Using FIT filename $FIT from env"
