creating filesystem at wb-prepare is fixed

diff --git a/board/prepare.init b/board/prepare.init
--- a/board/prepare.init
+++ b/board/prepare.init
@@ -125,21 +125,20 @@ wb_prepare_partitions()
     #    die "Prepare partitions failed"
     #}
     rm -f /tmp/partitions_backup
-    cat /tmp/partitions_backup 
+    
     PART3_SIZE=$(sed -n '3p' /tmp/disk_partitions | cut -d ' ' -f2)
     PART6_SIZE=$(sed -n '6p' /tmp/disk_partitions | cut -d ' ' -f2)
     mkswap /dev/mmcblk0p5
 
-    mkfs.ext4 /dev/mmcblk0p3 $PART3_SIZE
-    sleep 3
-    mkfs.ext4 /dev/mmcblk0p6 $PART6_SIZE
-    sleep 3 
-    mkfs.ext4 /dev/mmcblk0p3 -F
-    sleep 3
-    mkfs.ext4 /dev/mmcblk0p6 -F
-    sleep 3
-    echo "/dev/mmcblk0p6   /mnt/data   auto   errors=remount-ro,noatime   0   2" >> /etc/fstab
+    mkfs.ext4 /dev/mmcblk0p3 
+    mkfs.ext4 /dev/mmcblk0p6 
     
+    mount /dev/mmcblk0p6 /mnt/data
+    if [[ $? = "0" ]]; then
+        echo "/dev/mmcblk0p6   /mnt/data   auto   errors=remount-ro,noatime   0   2" >> /etc/fstab
+        touch $flag    
+    fi
+     
     log_success_msg "Partition table changed, reboot needed"
     fw_setenv bootcount 0
     reboot
@@ -317,10 +316,7 @@ wb_firstboot()
 {
     local flag="/var/lib/firstboot_done.flag"
 
-    [[ -f $flag ]] && return 0
-    
-    mount -a
-    [[ "$?" = "0" ]] && touch $flag
+    [[ -f $flag ]] && return 0 
 
     log_action_msg "Preparing rootfs for the first boot"
     service watchdog stop
@@ -381,7 +377,6 @@ wb_firstboot()
         done
     }
 
-    #touch $flag
     return 0
 }
 
