change confirmation choices

diff --git a/utils/bin/wb-factoryreset b/utils/bin/wb-factoryreset
--- a/utils/bin/wb-factoryreset
+++ b/utils/bin/wb-factoryreset
@@ -5,9 +5,12 @@ DIR_UPDATE="/mnt/data/.wb-update"
 
 if [[ "$1" != "--force" ]]; then
     echo "This will erase all your data and restore the system to factory defaults."
-    echo "Are you sure? (y/N)"
+    echo "Are you sure? (Yy/Nn)"
     read -r CONFIRM
-    [[ "$CONFIRM" == "y" ]] || exit 1
+    if [[ "$CONFIRM" != "y" && "$CONFIRM" != "Y" ]]; then
+        echo "Aborting"
+        exit 1
+    fi
 fi
 
 mkdir -p "$DIR_UPDATE"
