Fix modem watchdog

diff --git a/utils/bin/wb-gsm-mm b/utils/bin/wb-gsm-mm
--- a/utils/bin/wb-gsm-mm
+++ b/utils/bin/wb-gsm-mm
@@ -3,7 +3,16 @@
 watchdog() {
     while true; do
         if lsusb | grep -q "1e0e:9011"; then
-            systemd-notify WATCHDOG=1
+            if systemctl is-active --quiet ModemManager; then
+                output=$(mmcli -m wbc 2>&1)
+                if [ $? -ne 0 ] && [ "$output" = "error: couldn't find modem" ]; then
+                    echo "ModemManager is running, but modem is not found"
+                else
+                    systemd-notify WATCHDOG=1
+                fi
+            else
+                systemd-notify WATCHDOG=1
+            fi
         fi
         sleep $(($WATCHDOG_USEC / 3000000))
     done
