wb-run-update: support running without MQTT reporting

diff --git a/update/wb-run-update b/update/wb-run-update
--- a/update/wb-run-update
+++ b/update/wb-run-update
@@ -6,18 +6,47 @@ TMPDIR="/dev/shm"
 FIT=""
 FLAGS=""
 
+[[ $EUID != 0 ]] && die "Need root privileges to install update"
+
+while [[ -n "$1" ]]; do
+	case "$1" in
+		--*|-*)
+			FLAGS+="$1 "
+			;;
+		*)
+			[[ -n "$FIT" ]] && die "Bad arguments"
+			FIT=`readlink -f $1`
+			;;
+	esac
+	shift
+done
+
+[[ -n "$FIT" ]] || die "FIT $FIT not found"
+
 # Some handy functions, usable in install script
 rm_fit() {
 	info "Removing FIT $FIT"
 	rm -f "$FIT"
 }
 
-mqtt_status() {
-	mosquitto_pub -t /firmware/status -r -m "$*" 2>&1 >/dev/null || true
+flag_set() {
+	grep -- "--$1 " 2>&1 > /dev/null <<< "$FLAGS"
 }
 
-mqtt_progress() {
-	mosquitto_pub -t /firmware/progress -l 2>&1 >/dev/null || true
+flag_set no-mqtt && {
+	mqtt_status() { :; }
+
+	mqtt_progress() {
+		cat >/dev/null
+	}
+} || {
+	mqtt_status() {
+		mosquitto_pub -t /firmware/status -r -m "$*" 2>&1 >/dev/null || true
+	}
+
+	mqtt_progress() {
+		mosquitto_pub -t /firmware/progress -l 2>&1 >/dev/null || true
+	}
 }
 
 die() {
@@ -33,10 +62,6 @@ die() {
 info() {
 	>&2 echo ">>> $*"
 	mqtt_status "INFO $*"
-}
-
-flag_set() {
-	grep -- "--$1 " 2>&1 > /dev/null <<< "$FLAGS"
 }
 
 fit_prop() {
@@ -83,23 +108,6 @@ fit_blob_verify_hash() {
 		info "SHA1 hash of $name ok" ||
 		die "SHA1 of $name doesn't match (expected $sha1_expected, got $sha1_calculated)"
 }
-
-[[ $EUID != 0 ]] && die "Need root privileges to install update"
-
-while [[ -n "$1" ]]; do
-	case "$1" in
-		--*|-*)
-			FLAGS+="$1 "
-			;;
-		*)
-			[[ -n "$FIT" ]] && die "Bad arguments"
-			FIT=`readlink -f $1`
-			;;
-	esac
-	shift
-done
-
-[[ -n "$FIT" ]] || die "FIT $FIT not found"
 
 echo trigger > /sys/class/leds/green/trigger || true
 echo mmc0 > /sys/class/leds/red/trigger || true
